language: python
python:
  - "3.5"
sudo: required
services:
  - docker
branches:
  only:
  - sources
install:
- pip install pelican markdown
- pip install ghp-import
- git clone https://github.com/getpelican/pelican-plugins
script:
- make publish github
